# Generated by Django 3.1.1 on 2023-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Refid', models.CharField(help_text='student Id', max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Marks', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
